---
kind: pipeline
type: kubernetes
name: deploy demo
trigger:
  event:
    - push
  branch:
    - main

steps:

  - &deploy
    name: cs-demo
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.0
    environment:
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: cs-demo
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      ALLOWED_IPS:
        from_secret: ALLOWED_IPS
      RDS_CIDR:
        from_secret: RDS_CIDR_NOTPROD
      AWS_ACCOUNT:
        from_secret: AWS_ACCOUNT_NOTPROD
    commands:
      - bash -x helmfile-deploy.sh

  - <<: *deploy
    name: wcs-demo
    environment:
      KUBE_NAMESPACE: wcs-demo
    depends_on:
      - cs-demo
