name: 'Update QA Versions'
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION_FILE_PATH: './environments/qa/versions.yaml'

jobs:
  update:
    name: 'Update versions'
    runs-on: ubuntu-latest
    steps:

      - name: Set PR data
        run: |
          echo "PR_BRANCH=update_qa" >> ${GITHUB_ENV}
          echo "PR_TITLE=Update QA environment $(date +%d-%m-%Y)" >> ${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        shell: bash

      - name: Create a branch
        run: git checkout -b $PR_BRANCH
        shell: bash

      - name: Run update action
        uses: UKHomeOffice/update-helmfile-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_file_path: ${{ env.VERSION_FILE_PATH }}

      - name: Add all files
        run: |
          git add --all
          git commit -m "$PR_TITLE"
          git push --set-upstream origin $PR_BRANCH --force
        shell: bash

      - name: Create a PR
        run: gh pr edit $PR_BRANCH --title "$PR_TITLE" && gh pr reopen $PR_BRANCH || gh pr create --fill -B main -H $PR_BRANCH
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
